[package]
name    = "esp32"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"
publish = false

# [features]
# default = ["esp32"]
# esp32   = ["esp-backtrace/esp32", "esp-println/esp32", "esp-hal/esp32", "esp-hal-embassy/esp32", "esp-wifi/esp32"]
# esp32   = ["esp-hal/esp32",   "esp-backtrace/esp32",   "esp-hal-embassy?/esp32",   "esp-println/esp32",   "esp-storage?/esp32",   "esp-wifi?/esp32",   "esp-hal-smartled/esp32"]
# esp32c2 = ["esp-hal/esp32c2", "esp-backtrace/esp32c2", "esp-hal-embassy?/esp32c2", "esp-println/esp32c2", "esp-storage?/esp32c2", "esp-wifi?/esp32c2", ]
# esp32c3 = ["esp-hal/esp32c3", "esp-backtrace/esp32c3", "esp-hal-embassy?/esp32c3", "esp-println/esp32c3", "esp-storage?/esp32c3", "esp-wifi?/esp32c3", "esp-hal-smartled/esp32c3"]
# esp32c6 = ["esp-hal/esp32c6", "esp-backtrace/esp32c6", "esp-hal-embassy?/esp32c6", "esp-println/esp32c6", "esp-storage?/esp32c6", "esp-wifi?/esp32c6", "esp-hal-smartled/esp32c6", "esp-ieee802154/esp32c6"]
# esp32h2 = ["esp-hal/esp32h2", "esp-backtrace/esp32h2", "esp-hal-embassy?/esp32h2", "esp-println/esp32h2", "esp-storage?/esp32h2", "esp-wifi?/esp32h2", "esp-hal-smartled/esp32h2", "esp-ieee802154/esp32h2"]
# esp32s2 = ["esp-hal/esp32s2", "esp-backtrace/esp32s2", "esp-hal-embassy?/esp32s2", "esp-println/esp32s2", "esp-storage?/esp32s2", "esp-wifi?/esp32s2", "esp-hal-smartled/esp32s2"]
# esp32s3 = ["esp-hal/esp32s3", "esp-backtrace/esp32s3", "esp-hal-embassy?/esp32s3", "esp-println/esp32s3", "esp-storage?/esp32s3", "esp-wifi?/esp32s3", "esp-hal-smartled/esp32s3"]

[dependencies]
# sneakernet = {path=".."}

# esp dependencies
# esp-hal-embassy = {git="https://github.com/esp-rs/esp-hal.git", features=["integrated-timers"]}
# esp-backtrace = {git="https://github.com/esp-rs/esp-hal.git", features = ["panic-handler", "exception-handler", "println"]}
# esp-println = {git="https://github.com/esp-rs/esp-hal.git", features = ["log"]}
# # esp hardware interfaces
# esp-hal = {git="https://github.com/esp-rs/esp-hal.git"}
# esp-wifi = {git="https://github.com/esp-rs/esp-hal.git", features=["wifi"]}

# static_cell = { version = "2.1.0", features = ["nightly"] }

# non-esp dependencies
embassy-executor    = {version="0.5.0", features=["task-arena-size-40960"]}

[profile.release]
codegen-units    = 1
debug            = 2
debug-assertions = false
incremental      = false
opt-level        = 3
lto = 'fat'
overflow-checks  = false