[package]
name    = "free_library"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
embassy-time        = "0.3.1"
embassy-net = { version = "0.4.0", features = [ "tcp", "udp", "dhcpv4", "medium-ethernet"] }
heapless = { version = "0.8.0", default-features = false, features = [ "portable-atomic", ] }